### PR TITLE
Add Airline support

### LINKED ISSUE #15: Airline support
Thanks for the colour schemes. Could you please add vim-airline support?

### PR DESCRIPTION
**Pull request by kuglee**
Adds Airline support based on the `solarized` theme from [vim-airline-themes](https://github.com/vim-airline/vim-airline-themes).
Fixes #15.

### CODE REVIEW

**Comment by kdheepak** [comment]
I'm also interested in this! Thanks for making the PR.

I've tried this branch and I'm not able to get it to work locally. I can't see why though. Other colorschemes are loaded the exact same manner. I added a `echom "hello"` to the autoload file and it'd didn't print anything. For some reason this is not being loaded for me? I'm using the `xcodelighthc` colorscheme.

**Comment by arzg** [comment]
Thanks for the PR! Sorry it’s taken me so long to get around to this, but oh well.

I can’t figure out how exactly you generated the output in `autoload/` – it only works if I add a line like `Include: _airline_dark` to `xcodedark.colortemplate`.

I also noticed that there seems to be a _lot_ of duplication between the Airline themes. The only way I can think of to fix this is to allow `Include`d templates to have parameters. (I’ve opened an issue on Colortemplate for this: https://github.com/lifepillar/vim-colortemplate/issues/31)

Here’s what a unified Airline template might look like with the parameter syntax I proposed in that issue:

```
# in _airline.colortemplate
Params: warning modified insert visual replace
auxfile autoload/airline/themes/@shortname.vim
" Name:         @shortname
" Description:  @description
" Author:       @author
" Maintainer:   @maintainer
" License:      @license

let g:airline#themes#@shortname#palette = {}

function! airline#themes#@shortname#refresh()
  " Normal mode
  let s:N1 = ['@guibase0', '@guibase6', '']
  let s:N2 = [s:N1[0], '@guibase5', '']
  let s:N3 = ['@guibase7', '@guibase3', '']
  let s:NW = [s:N1[0], '$warning', '']
  let s:NM = ['$modified', s:N3[1], '']
  let s:NMi = s:NM

  " Insert mode
  let s:I1 = [s:N1[0], '$insert', '']
  let s:I2 = s:N2
  let s:I3 = s:N3
  let s:IM = s:NM

  " Visual mode
  let s:V1 = [s:N1[0], '$visual', '']
  let s:V2 = s:N2
  let s:V3 = s:N3
  let s:VM = s:NM

  " Replace mode
  let s:R1 = [s:N1[0], '$replace', '']
  let s:R2 = s:N2
  let s:R3 = s:N3
  let s:RM = s:NM

  " Inactive
  let s:IA = [s:N1[0], s:N3[1], '']

  let g:airline#themes#@shortname#palette.inactive = airline#themes#generate_color_map(
        \ [s:IA[0], s:IA[1], '', '', s:IA[2]],
        \ [s:IA[0], s:IA[1], '', '', s:IA[2]],
        \ [s:IA[0], s:IA[1], '', '', s:IA[2]])
  let g:airline#themes#@shortname#palette.inactive_modified = {
        \ 'airline_c': [s:NMi[0], '', '', '', s:NMi[2]]}

  let g:airline#themes#@shortname#palette.normal = airline#themes#generate_color_map(
        \ [s:N1[0], s:N1[1], '', '', s:N1[2]],
        \ [s:N2[0], s:N2[1], '', '', s:N2[2]],
        \ [s:N3[0], s:N3[1], '', '', s:N3[2]])

  let g:airline#themes#@shortname#palette.normal.airline_warning = [
        \ s:NW[0], s:NW[1], '', '', s:NW[2]]

  let g:airline#themes#@shortname#palette.normal.airline_error = [
        \ s:NW[0], s:NW[1], '', '', s:NW[2]]

  let g:airline#themes#@shortname#palette.normal_modified = {
        \ 'airline_c': [s:NM[0], s:NM[1], '', '', s:NM[2]]}

  let g:airline#themes#@shortname#palette.normal_modified.airline_warning =
        \ g:airline#themes#@shortname#palette.normal.airline_warning

  let g:airline#themes#@shortname#palette.insert = airline#themes#generate_color_map(
        \ [s:I1[0], s:I1[1], '', '', s:I1[2]],
        \ [s:I2[0], s:I2[1], '', '', s:I2[2]],
        \ [s:I3[0], s:I3[1], '', '', s:I3[2]])

  let g:airline#themes#@shortname#palette.insert.airline_warning =
        \ g:airline#themes#@shortname#palette.normal.airline_warning

  let g:airline#themes#@shortname#palette.insert_modified = {
        \ 'airline_c': [s:IM[0], s:IM[1], '', '', s:IM[2]]}

  let g:airline#themes#@shortname#palette.insert_modified.airline_warning =
        \ g:airline#themes#@shortname#palette.normal.airline_warning

  let g:airline#themes#@shortname#palette.visual = airline#themes#generate_color_map(
        \ [s:V1[0], s:V1[1], '', '', s:V1[2]],
        \ [s:V2[0], s:V2[1], '', '', s:V2[2]],
        \ [s:V3[0], s:V3[1], '', '', s:V3[2]])

  let g:airline#themes#@shortname#palette.visual.airline_warning =
        \ g:airline#themes#@shortname#palette.normal.airline_warning

  let g:airline#themes#@shortname#palette.visual_modified = {
        \ 'airline_c': [s:VM[0], s:VM[1], '', '', s:VM[2]]}

  let g:airline#themes#@shortname#palette.visual_modified.airline_warning =
        \ g:airline#themes#@shortname#palette.normal.airline_warning

  let g:airline#themes#@shortname#palette.replace = airline#themes#generate_color_map(
        \ [s:R1[0], s:R1[1], '', '', s:R1[2]],
        \ [s:R2[0], s:R2[1], '', '', s:R2[2]],
        \ [s:R3[0], s:R3[1], '', '', s:R3[2]])

  let g:airline#themes#@shortname#palette.replace.airline_warning =
        \ g:airline#themes#@shortname#palette.normal.airline_warning

  let g:airline#themes#@shortname#palette.replace_modified = {
        \ 'airline_c': [s:RM[0], s:RM[1], '', '', s:RM[2]]}

  let g:airline#themes#@shortname#palette.replace_modified.airline_warning =
        \ g:airline#themes#@shortname#palette.normal.airline_warning

  let g:airline#themes#@shortname#palette.tabline = {}

  let g:airline#themes#@shortname#palette.tabline.airline_tab = [
        \ s:I2[0], s:I2[1], '', '', s:I2[2]]

  let g:airline#themes#@shortname#palette.tabline.airline_tabtype = [
        \ s:N2[0], s:N2[1], '', '', s:N2[2]]
endfunction

call airline#themes#@shortname#refresh()
endauxfile
```

This can then be used like so:

```
# in _xcodedark.colortemplate

...

Include: _airline @guiorange @guilight_purple @guiyellow @guipink @guipurple
```

I decided against making all the `base<whatever>` colour usages parameters of the template, because all the colourschemes in vim-colors-xcode have them and as such would not vary between `Include` usages.

**Comment by kuglee** [comment]
> I can’t figure out how exactly you generated the output in `autoload/` – it only works if I add a line like `Include: _airline_dark` to `xcodedark.colortemplate`.

Sorry, I forgot to commit those changes. I committed them now.

> I also noticed that there seems to be a lot of duplication between the Airline themes. The only way I can think of to fix this is to allow Included templates to have parameters. (I’ve opened an issue on Colortemplate for this: lifepillar/vim-colortemplate#31)

Great idea.

P.S. Feel free to change the colors if you don't like them .

**Comment by arzg** [comment]
Turns out that if you have multiple `auxfile` blocks with the same path, the contents will be concatenated: https://github.com/lifepillar/vim-colortemplate/issues/31#issuecomment-656826951.

I think I’ll merge the changes for now, and I’ll fix the duplication later.

Thanks for your work on this PR :)

**Pull request merged**
